port: 5000
db:
  url: mongodb://root:password@localhost:27017/protocolServer?authSource=admin
app:
  mode: bap
  action: search

  privateKey: "O0DrMmoE5ieLwsqLmEloMnEe5HJSUzqdBHylPnl4usVmASaQNlx73+tSqjZ2UDu7gxVmGMXjskm0N+NegD6JPA=="
  publicKey: "ZgEmkDZce9/rUqo2dlA7u4MVZhjF47JJtDfjXoA+iTw="
  
  protocolId: "dev.bap.protocol-server.com"
  protocolUri: "https://ayush.free.beeceptor.com/"
  
  registryUrl: https://registry.becknprotocol.io/subscribers
  auth: true
  uniqueKey: "dev.bap.protocol-server.key"
  
  city: "Kochi"
  country: "IND"

  ttl: "P1M"
  lookupCacheTTL: "PT10S"

  httpTimeout: 3000
  httpRetryCount: 2
  
  callback:
    successUrl: "https://beckn.free.beeceptor.com/success"
    failureUrl: "https://beckn.free.beeceptor.com/failure"