port: 5000
db:
  url: mongodb://root:password@localhost:27017/protocolServer?authSource=admin
app:
  mode: bap

  actions:
    - search
    - init

  privateKey: "O0DrMmoE5ieLwsqLmEloMnEe5HJSUzqdBHylPnl4usVmASaQNlx73+tSqjZ2UDu7gxVmGMXjskm0N+NegD6JPA=="
  publicKey: "ZgEmkDZce9/rUqo2dlA7u4MVZhjF47JJtDfjXoA+iTw="

  subscriberId: "dev.bap.protocol-server.com"
  subscriberUri: "https://ayush.free.beeceptor.com/"
  
  registryUrl: https://registry.becknprotocol.io/subscribers
  auth: true
  uniqueKey: "dev.bap.protocol-server.key"
  
  city: "std:080"
  country: "IND"

  ttl: "P1M"
  lookupCacheTTL: "PT10S"

  httpTimeout: 3000
  httpRetryCount: 2
  
  clientUrl: "https://beckn.free.beeceptor.com/clientURL"