db:
  url: mongodb://root:password@192.168.0.15:27017/protocolServer?authSource=admin
app:
  mode: bap
  action: search

  privateKey: "O0DrMmoE5ieLwsqLmEloMnEe5HJSUzqdBHylPnl4usVmASaQNlx73+tSqjZ2UDu7gxVmGMXjskm0N+NegD6JPA=="
  publicKey: "ZgEmkDZce9/rUqo2dlA7u4MVZhjF47JJtDfjXoA+iTw="
  
  protocolId: "cabs.dev.bap.stayhalo.in"
  protocolUri: "https://beckn.free.beeceptor.com/"
  
  registryUrl: https://demo8386642.mockable.io
  auth: true
  uniqueKey: "134"
  
  city: "Kochi"
  country: "IND"
  ttl: "P1M"

  httpTimeout: 3000
  httpRetryCount: 2
  
  callback:
    successUrl: "https://beckn.free.beeceptor.com/success"
    failureUrl: "https://beckn.free.beeceptor.com/failure"